org: felipehenriquee
app: onthetable-backend
service: onthetable-backend

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 1024
  iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:PutObject
        Resource: "arn:aws:s3:::onthetable-images/*"


functions:
  main: 
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
          cors: true 
      - http:
          method: ANY
          path: '{proxy+}'
          cors: true 
